services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
    networks:
      - default-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    container_name: web
    restart: unless-stopped
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - default-network
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bash -c "rm -rf tmp/pids/server.pid && bin/setup && bundle exec rails s -b 0.0.0.0 -p 3000"
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle

  test:
    profiles: ["test"]
    build: .
    command: bundle exec rspec
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres13:
  redis_data:
  rubygems:

networks:
  default-network:
    driver: bridge